[[partner]]
name = "SODA Lab"
logo = "images/initiators/Logo_SODA.png"
url = "https://www.stat.lmu.de/soda"

[[partner]]
name = "LMU Munich"
logo = "images/initiators/Logo_LMU.svg"
url = "https://www.lmu.de"

[[partner]]
name = "BERD@NFDI"
logo = "images/initiators/Logo_BERD-NFDI.png"
url = "https://berd.nfdi.de"

[[partner]]
name = "byte"
logo = "images/initiators/Logo_byte.png"
url = "https://www.byte.bayern"

[[partner]]
name = "Bayerische Staatsministerium für Digitales"
logo = "images/initiators/Logo_StMD2.png"
url = "https://www.stmd.bayern.de"



[[client]]
name = "Staatliche Archive Bayerns"
logo = "images/initiators/Logo_GDA.gif"
url = "https://www.gda.bayern.de"


[[client]]
name = "Bayerisches Staatsministerium für Unterricht und Kultus"
logo = "images/initiators/Logo_StMUK.png"
url = "https://www.km.bayern.de"

[[client]]
name = "Bayerisches Staatsministerium für Familie, Arbeit und Soziales"
logo = "images/initiators/Logo_StMAS.png"
url = "https://www.stmas.bayern.de"

[[client]]
name = "Nationalpark Baerischer Wald"
logo = "images/initiators/Logo_Nationalpark.png"
url = "https://www.stmas.bayern.de"
